pull_request_rules:
  - name: automatic merge on CI success and review - Dependabot
    conditions:
      - check-success=Basaingeal.Razor.Clipboard
      - check-success=security/snyk (Basaingeal)
      - author~=^dependabot(|-preview)\[bot\]$
      - base=develop
    actions:
      merge:
        method: merge