pull_request_rules:
  - name: automatic merge on CI success and review - Dependabot
    conditions:
      - status-success=Basaingeal.Razor.Clipboard
      - status-success=deepcode-ci-bot
      - author=dependabot-preview[bot]
      - base=develop
    actions:
      merge:
        method: merge